---
name: Build and Deploy React App to GitHub Pages
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: npm install

    - name: Test
      run: npm run test

    - name: Deploy
      env:
        GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: |
        git config --global user.name 'Geoffrey Hazard'
        git config --global user.email 'geoffrey_hazard@alumni.brown.edu'
        git remote set-url origin https://github.com/${{ github.repository }}
        npm run deploy
